### ISSUE TITLE
Tap on Notification to see article

### ISSUE THREAD

**Issue by JoshGraham** [JonasCz/save-for-offline#10]
Tapping on notification does nothing;;
Maybe, by tapping on it, it shows article it saved.

**Comment by JonasCz** [comment]
I think it already does (in the latest source anyway) will check and fix it.

**Comment by JoshGraham** [comment]
Yes, you were right, sorry about that.
This issue was present at 2.0.2 Beta, fixed at 2.0.4 Beta
Though, at 2.0.4 Beta, tapping on notification goes to gridlayout, rather than the article.

logfile
https://gist.githubusercontent.com/JoshGraham/6f8e5cf14addf4b576f2/raw/5df11f6f908ed607cbcdae098c8dc4ee1e6a4355/gistfile1.txt

**Comment by JonasCz** [comment]
Will fix it. Thanks

**Comment by JonasCz** [comment]
This was in the app for a while, but was a pain to maintain, so I've taken it out for now.
