### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by nutpantz** [JonasCz/save-for-offline#13]
Link depth option
It would be nice to have an option to set link depth.
So that when downloading a webpage it will follow links on the page to the next page.
(Darn could not edit title , and I forgot to put the suggestion there)

**Comment by JonasCz** [comment]
No, unfortunately I am _very_ busy, and I don't have time for this now, as it would be a lot of work. Sometime in the future perhaps. There are other apps out there which let you do this though.
