### ISSUE TITLE
grate idea but not working

### ISSUE THREAD

**Issue by treakiandroid** [JonasCz/save-for-offline#14]
Hi,

This peace of software ive found and installed using fdroid repository is a really good idea and i would aprichiate it if it would work properly. Unfortunately it isnt working. If i share something to this app i get an uncloseable infinite forever notification that tells ne that it is saving the page. I cant cancel it, notching happens wen i click on it and if i open the main activity i get a crash. I would also send you some logcat output and screenshot if i had a mail address. I hope you can fix that and update the fix at fdroid. Thanks in advance

Treaki

**Comment by JonasCz** [comment]
Can you tell me what URL you are trying to save ?

**Comment by treakiandroid** [comment]
Normal articles, like they can be found on heise.de see #15 for logcat. I guess this has nothing to do with the.pages i try to save...

**Comment by JonasCz** [comment]
Should be fixed.
