### ISSUE TITLE
[feature request] Don't invert image colors in Night mode

### ISSUE THREAD

**Issue by ghost** [JonasCz/save-for-offline#18]

**Comment by JonasCz** [comment]
This may not actually be possible (Due to the way WebView works), but will see.

**Comment by ghost** [comment]
Thanks for considering it! :)

**Comment by JonasCz** [comment]
Ok, I did some research, and while it should be possible, it
- Would be a lot of work to implement this and maintain it, and
- Would probably make the rendering / displaying of saved pages horribly slow.

So, not for now I'm afraid. (At the moment I want to focus on making the app more stable and reliable, ie. to be able to save everything you try to save, which is not quite the case yet.)
