### ISSUE TITLE
Permit installing on external memory card.

### ISSUE THREAD

**Issue by Gitoffthelawn** [JonasCz/save-for-offline#27]
This excellent app is still small (yea!), but can you set the flag to allow it to be installed on an external memory card?

**Comment by JonasCz** [comment]
I'll take a look, this is easily doable. 

I'm curious though why you'd want to install a 500kb app (and I don't think it's going to become any bigger) on external memory ? (FYI, it already stores the bulk of its data on external memory).

**Comment by Gitoffthelawn** [comment]
Thanks.

Good question too.  Three reasons:
1. When internal memory is tight, every KB counts!
2. When searching through apps that are forced to be installed on internal memory, it makes that list longer (not a big deal, but the shorter the list, the better)
3. Open source projects can set good examples for closed source projects.  So many large apps force themselves to be installed on internal memory.  Many of them do not have a reason for this limitation (no widgets, etc.).  As it becomes more commonplace to remove this restriction, hopefully all developers will become aware of the flexibility they can offer their users.

**Comment by JonasCz** [comment]
Done (in the latest source).

**Comment by Gitoffthelawn** [comment]
Thanks!
