### ISSUE TITLE
Please, save-for-offline for Android 2.1

### ISSUE THREAD

**Issue by newbie222** [JonasCz/save-for-offline#32]
Hello, 
i am asking for this, because many people are using nowadays their rooted e-readers as internet browsers. The core OS in these readers is mainly Android 2.1, that's why i am appealing to the author of this beautiful program. If its not a difficult task or time consuming problem, please, Jonas , add support to this app for Android 2.1 !

Thanks in advance...!

**Comment by ghost** [comment]
+1

**Comment by JonasCz** [comment]
This is not something I realistically have time to do, unfortunately. Backporting apps to a (by now ancient) version of android takes quite a lot of effort.

Sorry folks :-(

**Comment by albertincx** [comment]
Guys, the world is changing and you have to change too. Using android 2.1 you stay in that time when this version was released.
Alas, it is now easier to create a new application from scratch under a new version of the operating system than to support the ancient versions.
