### ISSUE TITLE
Copy/paste

### ISSUE THREAD

**Issue by ghost** [JonasCz/save-for-offline#35]
Add an ability to copy/paste for the downloaded images or text files

**Comment by JonasCz** [comment]
You _can_ copy text from saved pages when viewing them in the app, text selection works the same way as in other apps - or do you mean something else ?

**Comment by ghost** [comment]
Mmh i undeestud, but don't work.. so os possible is the web page the problem?

**Comment by JonasCz** [comment]
I'll check again - I believe copy / paste does work for me, but I'll check to make sure

**Comment by ghost** [comment]
Thank you in any case
