### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by ghost** [JonasCz/save-for-offline#36]
Hi! Is possible add an ability to work with Orbot/I2P services, please??

**Comment by JonasCz** [comment]
See also: https://github.com/JonasCz/save-for-offline/issues/30

If you have [Orbot](https://play.google.com/store/apps/details?id=org.torproject.android&hl=en) installed, and have it set to send all traffic through TOR (VPN / Universal mode, I believe the feature is called), it should work with my app too, at least it did when I used it quite a while ago - have you tried this ?
