### ISSUE TITLE
'URL not valid' ever.

### ISSUE THREAD

**Issue by NitroNils** [JonasCz/save-for-offline#42]
Everytime I try to share it with your app, that error msg. pops up.

Browser:
UC Browser V11.3.0.950

Device:
PHONE_MODEL=ALE-L21
CUSTOM_DATA=
BRAND=Huawei
ANDROID_VERSION=6.0
APP_VERSION_NAME=0.103

[First Github post! Ever. ;]

**Comment by JonasCz** [comment]
Hmm, IIRC from having used UC browser for a while, it does the URL sharing in some non-standard way.

I might get around to making a workaround for this at some point, but now I'm just too busy :-(

You could copy-paste the url from UC and then use the "Add" button in my app. _I think_ UC browser has some sort of page-saving extension / plugin / addon available for it - maybe try that.

**Comment by NitroNils** [comment]
I ditched that spy ridden filth for Firefox Nightly. B)
