### ISSUE TITLE
Using setMediaPlaybackRequiresUserGesture() without API level check

### ISSUE THREAD

**Issue by LiliWeiSE** [JonasCz/save-for-offline#49]
Hi,

I just found that API setMediaPlaybackRequiresUserGesture() is directly invoked in ViewActivity. However, this API is introduced in API 17. (see: [here](https://developer.android.com/reference/android/webkit/WebSettings.html#setMediaPlaybackRequiresUserGesture(boolean)))
This will crash the app on devices with API level 16 (which is the min-sdk of save for offline).

Adding an API level check may help.

Thanks. :)

**Comment by JonasCz** [comment]
Thanks, fixed. I just removed setMediaPlaybackRequiresUserGesture(), since it isn't really needed anyhow.
