### ISSUE TITLE
Use a listview instead of gridlayout for smaller devce.

### ISSUE THREAD

**Issue by axkr** [JonasCz/save-for-offline#7]
Please use a listview instead of a gridlayout for at least screen classes "small" and "normal":

``` java
public String sizeClassificationText( Context ctx ) {
switch ( mSizeClass ) {
case Configuration.SCREENLAYOUT_SIZE_SMALL:
return "small";
case Configuration.SCREENLAYOUT_SIZE_NORMAL:
return "normal";
case Configuration.SCREENLAYOUT_SIZE_LARGE:
return "large";
case Configuration.SCREENLAYOUT_SIZE_XLARGE:
return "xlarge";
case Configuration.SCREENLAYOUT_SIZE_UNDEFINED:
return ctx.getString(R.string.undefined);
}
return ctx.getString(R.string.unknown);
}
```

**Comment by JonasCz** [comment]
Wired, I thought I was doing this already. Will look into it.

**Comment by axkr** [comment]
Ok it may already be a listview?
But this list view doesn't use the available space optimal. Only 4 list entries are displayed on a screen of height 640dp in portrait mode.
The titles of these items are displayed in the upper right corner? 
The size of the text would have allowed 7 lines of text to display in one list item?

Screen values are determined with Android ScreenInfo:
https://play.google.com/store/apps/details?id=com.jotabout.screeninfo

**Comment by JonasCz** [comment]
Post screenshot, because it works perfectly for me. Also , in case you don't know, there is an option in settings to change it.

**Comment by JonasCz** [comment]
Also, there is an option in settings to change it, in case you didn't know. If you want to put as many items as possible, there is an option for small list without thumbnails.

**Comment by axkr** [comment]
Ok "List no thumbnails" is the best option for me. You can close this item.

**Comment by JonasCz** [comment]
Are the thumbnails not showing with any of the other options? That would be bad...

**Comment by JonasCz** [comment]
Closing for now as no message back, I can assume this is fixed. Let me know if it isn't.
