### ISSUE TITLE
enhancement : Night View

### ISSUE THREAD

**Issue by JoshGraham** [JonasCz/save-for-offline#8]
enhancement suggestion
Night(Dark) view
Would love to ditch Pocket for this :)

**Comment by JonasCz** [comment]
Yep, sure! Will have to figure out how to do this though. (Should not be too hard. :+1:  )

**Comment by JonasCz** [comment]
OK. Started on it , still needs some work tho.
![screenshot_2015-02-23-11-24-33](https://cloud.githubusercontent.com/assets/10514959/6326941/b4ee0260-bb4e-11e4-8d07-2a9509160e1d.png)
![screenshot_2015-02-23-11-25-05](https://cloud.githubusercontent.com/assets/10514959/6326948/c01885de-bb4e-11e4-8b9f-c46c494cb616.png)

**Comment by JonasCz** [comment]
Done, in the source anyway. Fixed the action bar background color, and various other places. Will upload release soon.
